[manager]
ratio           = [ 2, 3, 6 ]
sort_by         = "natural"
sort_sensitive  = false
sort_reverse    = false
sort_dir_first  = true
linemode        = "size"
show_symlink    = false

[preview]
max_width = 800
max_height = 800
sixel_fraction = 14
image_filter = "triangle"
cache_dir = "~/.cache/yazi/"

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
  { mime = "audio/*", run = "exifaudio" },

	{ mime = "application/zip",             run = "ouch" },
	{ mime = "application/gzip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip",          run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
]
