#! /bin/sh

#  █████████  ████████ █████████ ██ ██████████████
#  ██     ██  ██       ██     ██ ██ ██    ██    ██
#  ██     ██  ██       ██     ██ ██ ██ ██ ██ ██ ██
#  ██████████ ████████ █████████ ██ ██ ██ ██ ██ ██
#  ██      ██       ██ ██        ██ ██ ██ ██ ██ ██
#  ██      ██       ██ ██        ██    ██    ██ ██
#  ██████████ ████████ ██        ██████████████ ██

# env
export $(envsubst < $HOME/.config/bspwm/env)

# Secrets
export $(envsubst < $HOME/.config/bspwm/secrets)

setxkbmap -layout "gb" &&
numlockx &
pgrep -x sxhkd >/dev/null || sxhkd &
wmname LG3D &

######## bspwm ########
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width 2
bspc config window_gap 4
bspc config normal_border_color \#565f89
bspc config active_border_color \#7dcfff
bspc config focused_border_color \#7aa2f7
bspc config presel_feedback_color \#7aa2f7

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
# bspc config focus_follows_pointer true
bspc config pointer_motion_interval 16 

bspc desktop 十 -l next
bspc desktop 一 -l next

#### Window Rules #####
##  floating rules   ##
bspc rule -a file-roller state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a pavucontrol state=floating
# bspc rule -a Nemo state=floating
bspc rule -a Audacious state=floating
bspc rule -a qBittorrent state=floating
bspc rule -a Engrampa state=floating
bspc rule -a Bulky.py state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Quigo state=floating

bspc rule -a thunderbird:Mail:"About Mozilla Thunderbird" state=floating
bspc rule -a firefox:Browser:"About Mozilla Firefox" state=floating
bspc rule -a zenity border=off state=floating

bspc rule -a Surf state=tiled
bspc rule -a Spotube state=tiled

bspc rule -a firefox desktop='^1'
bspc rule -a thunderbird desktop='^10'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

####### Auto start #######
#dbus-update-activation-environment DISPLAY XAUTHORITY WAYLAND_DISPLAY &
~/.fehbg &
~/.config/polybar/launch.sh &
# enable after update 
/usr/bin/cp ~/.config/conky/Mimosa/scripts/rings-v1.2.1.lua /tmp
/usr/bin/conky -c ~/.config/conky/Mimosa/Mimosa.conf &
/usr/bin/xsetroot -cursor_name left_ptr &
/usr/bin/picom --config ~/.config/picom/picom.conf &
/usr/bin/mpd --no-daemon &
/usr/bin/otd-daemon &
/usr/bin/lxpolkit &
/usr/bin/nm-applet &
/usr/bin/xfce4-power-manager &
/usr/bin/parcellite &
/usr/bin/keepassxc &
/usr/bin/thunderbird &
# /usr/bin/discord --start-minimized &
/usr/bin/xss-lock -- betterlockscreen -l dimblur --quiet --off 5
