return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "vim",
        "lua",
        "vimdoc",
        "html",
        "css",
        "javascript",
        "typescript",
        "json",
        "jsonc",
        "yaml",
        "toml",
        "python",
        "rust",
        "c",
        "cpp",
        "bash",
        "fish",
        "go",
        "templ",
        "svelte",
        "markdown",
        "markdown_inline",
        "sql",
        "gomod",
      },
    },
  },
}
